// <auto-generated />
using System;
using AnimalShelter.src.Shared.DbLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.src.Shared.DbLayer.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AnimalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CanFly")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsIndoor")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNocturnal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            Breed = "Golden Retriever",
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(119),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Max",
                            Size = 2,
                            Species = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(121)
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Color = "Black and White",
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(126),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsIndoor = true,
                            Name = "Luna",
                            Species = 1,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(127)
                        },
                        new
                        {
                            Id = 3,
                            Age = 1,
                            CanFly = true,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(131),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Rio",
                            Species = 2,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(133)
                        });
                });

            modelBuilder.Entity("AnimalShelter.src.Models.Adoption", b =>
                {
                    b.Property<int>("AdoptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdoptionId"));

                    b.Property<DateTime>("AdoptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdoptionId");

                    b.HasIndex("AnimalId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Adoptions");
                });

            modelBuilder.Entity("AnimalShelter.src.Models.CareNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("CareNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(266),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Needs at least 30 minutes of daily exercise. Loves playing fetch.",
                            IsDeleted = false,
                            Title = "Daily Exercise",
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(268)
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 2,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(272),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Allergic to chicken. Feed only fish-based food.",
                            IsDeleted = false,
                            Title = "Special Diet",
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(273)
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 3,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(277),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Needs a large cage with space to fly. Prefers morning sun.",
                            IsDeleted = false,
                            Title = "Cage Requirements",
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(278)
                        });
                });

            modelBuilder.Entity("AnimalShelter.src.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoleName")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 9, 797, DateTimeKind.Local).AddTicks(5946),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleName = 1,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 9, 797, DateTimeKind.Local).AddTicks(5948)
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 9, 797, DateTimeKind.Local).AddTicks(5953),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleName = 2,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 9, 797, DateTimeKind.Local).AddTicks(5954)
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 9, 797, DateTimeKind.Local).AddTicks(5958),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleName = 0,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 9, 797, DateTimeKind.Local).AddTicks(5959)
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 9, 927, DateTimeKind.Local).AddTicks(5938),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 9, 927, DateTimeKind.Local).AddTicks(6038),
                            UserEmail = "john.admin@animalshelter.com",
                            UserName = "admin_john",
                            UserPassword = "$2a$11$K7EluGDZikTYuvI.dgNW8O/jLSKEPTL03CMx6KmFHP1PlDWaH1Z3W"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 45, DateTimeKind.Local).AddTicks(1928),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 45, DateTimeKind.Local).AddTicks(2030),
                            UserEmail = "sarah.admin@animalshelter.com",
                            UserName = "admin_sarah",
                            UserPassword = "$2a$11$S366zA8udR1DYA/3OYegzuggJT5s1ls0LBkalwWRNnTanzL2dOkre"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 174, DateTimeKind.Local).AddTicks(7795),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 174, DateTimeKind.Local).AddTicks(7891),
                            UserEmail = "mike.employee@animalshelter.com",
                            UserName = "employee_mike",
                            UserPassword = "$2a$11$QcTo7mobeq/6.esU3fPpQ.aytwsNO9oJfrzjE9FDnGDltjwGJj1r2"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 303, DateTimeKind.Local).AddTicks(3875),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 303, DateTimeKind.Local).AddTicks(3963),
                            UserEmail = "lisa.employee@animalshelter.com",
                            UserName = "employee_lisa",
                            UserPassword = "$2a$11$uby4o6683yPjssA25dPAVOrQVsx7gXXcVlCEfR2qNUoBQzm6OMWAi"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 432, DateTimeKind.Local).AddTicks(3030),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleId = 3,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 432, DateTimeKind.Local).AddTicks(3118),
                            UserEmail = "emma.user@example.com",
                            UserName = "user_emma",
                            UserPassword = "$2a$11$1R1l3Od.mF1z/ORy/KHIZumNbt7VfRA7r8CnOkbxa3NdCTDCH91pS"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 556, DateTimeKind.Local).AddTicks(1141),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleId = 3,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 556, DateTimeKind.Local).AddTicks(1241),
                            UserEmail = "james.user@example.com",
                            UserName = "user_james",
                            UserPassword = "$2a$11$Spo5eeFBV6R5gT4FulvoGO.ie5TvRUGKnvjFBns1OQqKl.K/LaDBa"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 681, DateTimeKind.Local).AddTicks(9122),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RoleId = 3,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 681, DateTimeKind.Local).AddTicks(9219),
                            UserEmail = "sophia.user@example.com",
                            UserName = "user_sophia",
                            UserPassword = "$2a$11$FHtY7ArLHNrN1wS0F94HueBYG2iXLo2FLWBFSdXyK6Bv2eTgzZaK6"
                        });
                });

            modelBuilder.Entity("Vaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VaccineDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaccineDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccineId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Vaccines");

                    b.HasData(
                        new
                        {
                            VaccineId = 1,
                            AnimalId = 1,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(199),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(201),
                            VaccineDate = new DateTime(2026, 3, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(191),
                            VaccineDescription = "Rabies vaccination",
                            VaccineName = "Rabies"
                        },
                        new
                        {
                            VaccineId = 2,
                            AnimalId = 1,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(207),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(209),
                            VaccineDate = new DateTime(2026, 4, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(205),
                            VaccineDescription = "Canine distemper vaccination",
                            VaccineName = "Distemper"
                        },
                        new
                        {
                            VaccineId = 3,
                            AnimalId = 2,
                            CreatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(215),
                            CreatedBy = "System",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 5, 30, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(217),
                            VaccineDate = new DateTime(2026, 2, 28, 17, 42, 10, 682, DateTimeKind.Local).AddTicks(213),
                            VaccineDescription = "Feline viral rhinotracheitis, calicivirus, and panleukopenia",
                            VaccineName = "FVRCP"
                        });
                });

            modelBuilder.Entity("AnimalShelter.src.Models.Adoption", b =>
                {
                    b.HasOne("Animal", "Animal")
                        .WithOne("Adoption")
                        .HasForeignKey("AnimalShelter.src.Models.Adoption", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Adoptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimalShelter.src.Models.CareNote", b =>
                {
                    b.HasOne("Animal", "Animal")
                        .WithMany("CareNotes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("AnimalShelter.src.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Vaccine", b =>
                {
                    b.HasOne("Animal", "Animal")
                        .WithMany("Vaccines")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Animal", b =>
                {
                    b.Navigation("Adoption");

                    b.Navigation("CareNotes");

                    b.Navigation("Vaccines");
                });

            modelBuilder.Entity("AnimalShelter.src.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Adoptions");
                });
#pragma warning restore 612, 618
        }
    }
}
